name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: rust-cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
    
      - name: run tests
        run: cargo test

